name: Database

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: 2.106.0
      - run: supabase start
      - run: supabase db reset
      - run: supabase test db
